//! Resource modules

pub mod insight_rules;
pub use insight_rules::Insight_rules;
pub mod alarm_contributors;
pub use alarm_contributors::Alarm_contributors;
pub mod dashboard;
pub use dashboard::Dashboard;
pub mod metric_data;
pub use metric_data::Metric_data;
pub mod alarms_for_metric;
pub use alarms_for_metric::Alarms_for_metric;
pub mod metric_stream;
pub use metric_stream::Metric_stream;
pub mod alarms;
pub use alarms::Alarms;
pub mod metric_statistics;
pub use metric_statistics::Metric_statistics;
pub mod composite_alarm;
pub use composite_alarm::Composite_alarm;
pub mod insight_rule;
pub use insight_rule::Insight_rule;
pub mod metric_alarm;
pub use metric_alarm::Metric_alarm;
pub mod dashboards;
pub use dashboards::Dashboards;
pub mod anomaly_detectors;
pub use anomaly_detectors::Anomaly_detectors;
pub mod insight_rule_report;
pub use insight_rule_report::Insight_rule_report;
pub mod anomaly_detector;
pub use anomaly_detector::Anomaly_detector;
pub mod metric_widget_image;
pub use metric_widget_image::Metric_widget_image;
pub mod managed_insight_rules;
pub use managed_insight_rules::Managed_insight_rules;
pub mod alarm_history;
pub use alarm_history::Alarm_history;

