//! Resource modules

pub mod package_group;
pub use package_group::Package_group;
pub mod repository_permissions_policy;
pub use repository_permissions_policy::Repository_permissions_policy;
pub mod package_version_asset;
pub use package_version_asset::Package_version_asset;
pub mod package_version_readme;
pub use package_version_readme::Package_version_readme;
pub mod domain;
pub use domain::Domain;
pub mod package;
pub use package::Package;
pub mod package_versions;
pub use package_versions::Package_versions;
pub mod package_origin_configuration;
pub use package_origin_configuration::Package_origin_configuration;
pub mod repository_endpoint;
pub use repository_endpoint::Repository_endpoint;
pub mod repository;
pub use repository::Repository;
pub mod associated_package_group;
pub use associated_package_group::Associated_package_group;
pub mod package_versions_status;
pub use package_versions_status::Package_versions_status;
pub mod authorization_token;
pub use authorization_token::Authorization_token;
pub mod package_group_origin_configuration;
pub use package_group_origin_configuration::Package_group_origin_configuration;
pub mod domain_permissions_policy;
pub use domain_permissions_policy::Domain_permissions_policy;
pub mod package_version;
pub use package_version::Package_version;

